AppOficina/urls.py
from django.urls import path
from AppOficina.views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', home, name='home'),
    path('about', about, name='about'),
    # URLS para ingresar registros
    path('setVidejouego/', setVidejouego, name='videojuego'),
    path('setConsola/', setConsola, name='consola'),
    path('setDesarrollador/', setDesarrollador, name='desarrollador'),
    path('setPersonaje/', setPersonaje, name='personaje'),
    # URLS para buscar registros
    path('buscarVideojuego/', buscarVideojuego, name='buscarVideojuego'),
    path('buscar/', buscar),
    path('registro/', registro, name='registro'),
    # URLS para ver y editar registros
    path('leervideojuegos/', leerVideojuegos, name='leerVideojuegos'),
    path('eliminarVideojuego/<nombreVideojuego>',eliminarVideojuego, name='eliminarVideojuego'),
    path('editarVideojuego/<nombreVideojuego>',updateVidejuego, name='editarVideojuego'),
    path('busqueda/', busqueda, name='busqueda'),
    path('buscarDesarrollador/', buscarDesarrollador, name='buscarDesarrollador'),
    path('buscarDesarrolladores/', buscarDesarrolladores),
    path('leerDesarrolladores/', leerDesarrolladores, name='leerDesarrolladores'),
    path('eliminarDesarrollador/<nombreDesarrollador>',eliminarDesarrollador, name='eliminarDesarrollador'),
    path('editarDesarrollador/<nombreDesarrollador>',updateDesarrollador, name='editarDesarrollador'),
    path('buscarPersonaje/', buscarPersonaje, name='buscarPersonaje'),
    path('buscarPersonajes/', buscarPersonajes),
    path('leerPersonajes/', leerPersonajes, name='leerPersonajes'),
    path('eliminarPersonaje/<nombrePersonaje>',eliminarPersonaje, name='eliminarPersonaje'),
    path('editarPersonaje/<nombrePersonaje>',updatePersonaje, name='editarPersonaje'),
    path('buscarConsola/', buscarConsola, name='buscarConsola'),
    path('buscarConsolas/', buscarConsolas),
    path('leerConsolas/', leerConsolas, name='leerConsolas'),
    path('eliminarConsola/<nombreConsola>',eliminarConsola, name='eliminarConsola'),
    path('editarConsola/<nombreConsola>',updateConsola, name='editarConsola'),
    # URLS pararegistro, edición y creación de usuarios
    path('login/', loginRequest, name="login"),
    path('registrar/', register, name="Signout"),
    path('logout/', LogoutView.as_view(template_name="AppOficina/logout.html"), name="logout"),
    path('editar/', editarUser, name="editarUser"),
    path('avatar/', agregarAvatar, name="avatar"),

]

OficinaGamer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('AppOficina/', include('AppOficina.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'AppOficina.views.error404'
handler400 = 'AppOficina.views.error404'

AppOficina/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Videojuego(models.Model):
    nombre = models.CharField(max_length=50)
    lanzamiento = models.DateField()
    plataforma = models.CharField(max_length=40)
    desarrollador = models.CharField(max_length=40)
    genero = models.CharField(max_length=40)

    def __str__(self):
        return f"Videojuego: {self.nombre} | Genero: {self.genero}"


class Desarrollador(models.Model):
    nombre = models.CharField(max_length=50)
    fundada = models.DateField()
    pais = models.CharField(max_length=40)

    def __str__(self):
        return f"Desarrollador: {self.nombre}"


class Consola(models.Model):
    nombre = models.CharField(max_length=50)
    lanzamiento = models.DateField()
    marca = models.CharField(max_length=40)

    def __str__(self):
        return f"Consola: {self.nombre}"


class Personaje(models.Model):
    nombre = models.CharField(max_length=50)
    videojuego = models.CharField(max_length=40)
    plataforma = models.CharField(max_length=40)

    def __str__(self):
        return f"Personaje: {self.nombre}"


class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='avatares', null=True, blank=True)

AppOficina/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from AppOficina.models import Avatar


class DateInput(forms.DateInput):
    input_type = 'date'


class FormVidejuego(forms.Form):
    nombre = forms.CharField()
    lanzamiento = forms.DateField(widget=DateInput)
    plataforma = forms.CharField()
    desarrollador = forms.CharField()
    genero = forms.CharField()


class FormDesarrollador(forms.Form):
    nombre = forms.CharField()
    fundada = forms.DateField(widget=DateInput)
    pais = forms.CharField()


class FormConsola(forms.Form):
    nombre = forms.CharField()
    lanzamiento = forms.DateField(widget=DateInput)
    marca = forms.CharField()


class FormPersonaje(forms.Form):
    nombre = forms.CharField()
    videojuego = forms.CharField()
    plataforma = forms.CharField()


class FormRegistroUser(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Repetir contraseña", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name',
                  'password1', 'password2']
        help_texts = {k: "" for k in fields}


class FormEditarUser(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Repetir contraseña", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name',
                  'password1', 'password2']
        help_texts = {k: "" for k in fields}


class FormAvatar(forms.ModelForm):

    class Meta:
        model = Avatar
        fields = ['image']

AppOficina/views.py
from django.shortcuts import render
from django.http import HttpResponse
from AppOficina.forms import *
from AppOficina.models import *
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required


# Login, Logout, registro de usuarios
def loginRequest(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():  # Si pasó la validación de Django
            usuario = form.cleaned_data.get('username')
            contrasenia = form.cleaned_data.get('password')
            user = authenticate(username=usuario, password=contrasenia)
            if user is not None:
                login(request, user)
                return render(request, "AppOficina/home.html", {"mensaje": f"Bienvenido {usuario}"})
            else:
                return render(request, "AppOficina/home.html", {"mensaje": "Datos incorrectos"})
        else:
            return render(request, "AppOficina/home.html", {"mensaje": "Formulario erroneo"})
    form = AuthenticationForm()
    return render(request, "AppOficina/login.html", {"form": form})


def register(request):
    if request.method == 'POST':
        form = FormRegistroUser(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            form.save()
            return render(request, "AppOficina/home.html",  {"mensaje": "Usuario cambiado)"})
    else:
        form = FormRegistroUser()
    return render(request, "AppOficina/registrar.html",  {"form": form})


@login_required
def editarUser(request):
    user = request.user
    if request.method == 'POST':
        form = FormEditarUser(request.POST)
        if form.is_valid():
            info = form.cleaned_data
            user.email = info['email']
            user.set_password(info['password1'])
            user.first_name = info['first_name']
            user.last_name = info['last_name']
            user.save()
            return render(request, "AppOficina/home.html",  {"mensaje": f"Usuario "})
    else:
        form = FormEditarUser(initial={
            'email': user.email, 'first_name': user.first_name, 'last_name': user.last_name})
    return render(request, "AppOficina/editarPerfil.html",  {"form": form, "user": user})


@login_required
def agregarAvatar(request):
    if request.method == 'POST':
        form = FormAvatar(request.POST, request.FILES)
        if form.is_valid():
            currentUser = User.objects.get(username=request.user)
            avatar = Avatar(user=currentUser, image=form.cleaned_data['image'])
            avatar.save()
            return render(request, "AppOficina/home.html")
    else:
        form = FormAvatar()
    return render(request, "AppOficina/agregarAvatar.html",  {"form": form})

# Páginas de inicio, error y sobre mi


def home(request):
    return render(request, "AppOficina/home.html")


def error404(request, exception):
    return render(request, "AppOficina/404.html")


def error400(request, exception):
    return render(request, "AppOficina/400.html")


def about(request):
    return render(request, "AppOficina/about.html")


def registro(request):
    return render(request, "AppOficina/registro.html")


def busqueda(request):
    return render(request, "AppOficina/busqueda.html")

# Modelos


def setVidejouego(request):
    if request.method == "POST":
        myForm = FormVidejuego(request.POST)
        if myForm.is_valid():
            info = myForm.cleaned_data
            videojuego = Videojuego(**info)
            videojuego.save()
            return render(request, "AppOficina/registro.html")
    else:
        myForm = FormVidejuego()
    return render(request, "AppOficina/videojuego.html", {"myForm": myForm})


def setDesarrollador(request):
    if request.method == "POST":
        myForm = FormDesarrollador(request.POST)
        if myForm.is_valid():
            info = myForm.cleaned_data
            desarrollador = Desarrollador(**info)
            desarrollador.save()
            return render(request, "AppOficina/registro.html")
    else:
        myForm = FormDesarrollador()
    return render(request, "AppOficina/desarrollador.html", {"myForm": myForm})


def setConsola(request):
    if request.method == "POST":
        myForm = FormConsola(request.POST)
        if myForm.is_valid():
            info = myForm.cleaned_data
            consola = Consola(**info)
            consola.save()
            return render(request, "AppOficina/registro.html")
    else:
        myForm = FormConsola()
    return render(request, "AppOficina/consola.html", {"myForm": myForm})


def setPersonaje(request):
    if request.method == "POST":
        myForm = FormPersonaje(request.POST)
        if myForm.is_valid():
            info = myForm.cleaned_data
            personaje = Personaje(**info)
            personaje.save()
            return render(request, "AppOficina/registro.html")
    else:
        myForm = FormPersonaje()
    return render(request, "AppOficina/personajes.html", {"myForm": myForm})


# CRUD Videojuegos
def buscarVideojuego(request):
    return render(request, "AppOficina/buscarVideojuego.html")


def buscar(request):
    if request.GET['videojuego']:
        consulta = request.GET['videojuego']
        resultados = Videojuego.objects.filter(nombre__icontains=consulta)
        return render(request, "AppOficina/resultadoVideojuego.html", {"consulta": consulta, "resultados": resultados})
    else:
        respuesta = "No datos recopilados"
    return HttpResponse(respuesta)


@login_required
def leerVideojuegos(request):
    videojuegos = Videojuego.objects.all()
    contexto = {"videojuegos": videojuegos}
    return render(request, "AppOficina/leerVideojuego.html", contexto)


def eliminarVideojuego(request, nombreVideojuego):
    videojuego = Videojuego.objects.get(nombre=str(nombreVideojuego))
    videojuego.delete()
    videojuegos = Videojuego.objects.all()
    contexto = {"videojuegos": videojuegos}
    return render(request, "AppOficina/leerVideojuego.html", contexto)


def updateVidejuego(request, nombreVideojuego):
    videojuego = Videojuego.objects.get(nombre=str(nombreVideojuego))

    if request.method == "POST":
        myForm = FormVidejuego(request.POST)
        if myForm.is_valid():
            info = myForm.cleaned_data
            videojuego.nombre = info['nombre']
            videojuego.lanzamiento = info['lanzamiento']
            videojuego.plataforma = info['plataforma']
            videojuego.desarrollador = info['desarrollador']
            videojuego.genero = info['genero']
            videojuego.save()
            return render(request, "AppOficina/registro.html")
    else:
        myForm = FormVidejuego(initial={
                               'nombre': videojuego.nombre, 'lanzamiento': videojuego.lanzamiento, 'plataforma': videojuego.plataforma, 'desarrollador': videojuego.desarrollador, 'genero': videojuego.genero})
    return render(request, "AppOficina/editarVideojuego.html", {"myForm": myForm, "nombreVideojuego": nombreVideojuego})

# CRUD Desarrolladores


def buscarDesarrollador(request):
    return render(request, "AppOficina/buscarDesarrollador.html")


def buscarDesarrolladores(request):
    if request.GET['desarrollador']:
        consulta = request.GET['desarrollador']
        resultados = Desarrollador.objects.filter(nombre__icontains=consulta)
        return render(request, "AppOficina/resultadoDesarrollador.html", {"consulta": consulta, "resultados": resultados})
    else:
        respuesta = "No datos recopilados"
    return HttpResponse(respuesta)


@login_required
def leerDesarrolladores(request):
    desarrolladores = Desarrollador.objects.all()
    contexto = {"desarrolladores": desarrolladores}
    return render(request, "AppOficina/leerDesarrollador.html", contexto)


def eliminarDesarrollador(request, nombreDesarrollador):
    desarrollador = Desarrollador.objects.get(nombre=str(nombreDesarrollador))
    desarrollador.delete()
    desarrolladores = Desarrollador.objects.all()
    contexto = {"desarrolladores": desarrolladores}
    return render(request, "AppOficina/leerDesarrollador.html", contexto)


def updateDesarrollador(request, nombreDesarrollador):
    desarrollador = Desarrollador.objects.get(nombre=str(nombreDesarrollador))
    if request.method == "POST":
        myForm = FormDesarrollador(request.POST)
        if myForm.is_valid():
            info = myForm.cleaned_data
            desarrollador.nombre = info['nombre']
            desarrollador.fundada = info['fundada']
            desarrollador.pais = info['pais']
            desarrollador.save()
            return render(request, "AppOficina/registro.html")
    else:
        myForm = FormDesarrollador(initial={
            'nombre': desarrollador.nombre, 'fundada': desarrollador.fundada, 'pais': desarrollador.pais})
    return render(request, "AppOficina/editarDesarrollador.html", {"myForm": myForm, "nombreDesarrollador": nombreDesarrollador})


# CRUD Personajes
def buscarPersonaje(request):
    return render(request, "AppOficina/buscarPersonaje.html")


def buscarPersonajes(request):
    if request.GET['personaje']:
        consulta = request.GET['personaje']
        resultados = Personaje.objects.filter(nombre__icontains=consulta)
        return render(request, "AppOficina/resultadoPersonaje.html", {"consulta": consulta, "resultados": resultados})
    else:
        respuesta = "No datos recopilados"
    return HttpResponse(respuesta)


@login_required
def leerPersonajes(request):
    personajes = Personaje.objects.all()
    contexto = {"personajes": personajes}
    return render(request, "AppOficina/leerPersonaje.html", contexto)


def eliminarPersonaje(request, nombrePersonaje):
    personaje = Personaje.objects.get(nombre=str(nombrePersonaje))
    personaje.delete()
    personajes = Personaje.objects.all()

AppOficina/templates/AppOficina/about.html
{% extends "AppOficina/plantilla.html" %} {% load static %} {% block main %}
<div>
  <h2>Miguel Angel Contreras Cruz</h2>
  <p style="font-size: 20px">
    Licenciado en diseño gráfico por la Benemérita Universidad Autónoma de
    Puebla. Es miembro de los colectivos Letter INC, Letrástica y Typefobia
    orientado a actividades en torno a la caligrafía, tipografía y rotulación,
    donde imparte talleres, organiza el encuentros y charlas. Actualmente se
    desempeña como experto tipográfico en Cultivo Estudio, front end developer
    en InterplanetaryFonts y junto con Eduardo Aire fundó Letter Engine, una
    fundición tipográfica independiente especializada en font production,
    mastering y programación.
  </p>
</div>

{% endblock %}

AppOficina/templates/AppOficina/buscarConsola.html
{% extends "AppOficina/plantilla.html" %} {% load static %} {% block main %}

<div>
  <h4>Buscar consolas por nombre</h4>
  <form action="/AppOficina/buscarConsolas" method="GET">
    <input type="text" name="consola" id="consola" />
    <input type="submit" value="Buscar" />
  </form>
</div>

{% endblock %}

AppOficina/templates/AppOficina/buscarDesarrollador.html
{% extends "AppOficina/plantilla.html" %} {% load static %} {% block main %}

<div>
  <h4>Buscar desarrolladores por nombre</h4>
  <form action="/AppOficina/buscarDesarrolladores" method="GET">
    <input type="text" name="desarrollador" id="desarrollador" />
    <input type="submit" value="Buscar" />
  </form>
</div>

{% endblock %}

AppOficina/templates/AppOficina/buscarPersonaje.html
{% extends "AppOficina/plantilla.html" %} {% load static %} {% block main %}

<div>
  <h4>Buscar personajes por nombre</h4>
  <form action="/AppOficina/buscarPersonajes" method="GET">
    <input type="text" name="personaje" id="personaje" />
    <input type="submit" value="Buscar" />
  </form>
</div>

{% endblock %}

AppOficina/templates/AppOficina/buscarVideojuego.html
{% extends "AppOficina/plantilla.html" %} {% load static %} {% block main %}

<div>
  <h4>Buscar videojuegos por nombre</h4>
  <form action="/AppOficina/buscar" method="GET">
    <input type="text" name="videojuego" id="videojuego" />
    <input type="submit" value="Buscar" />
  </form>
</div>

{% endblock %}

AppOficina/templates/AppOficina/desarrollador.html
{% extends "AppOficina/plantilla.html" %} {% load static %}

{% block main %} 
{% if myForm.errors %}
<h1>Error en formulario</h1>
{% endif %}

<div >
  <form action="" method="POST">
    {% csrf_token %} {{ myForm.as_table }}

    <input type="submit" value="Registrar" />
  </form>
</div>
{% endblock %}

AppOficina/templates/AppOficina/editarPersonaje.html
{% extends "AppOficina/plantilla.html" %} {% load static %} 


{% block main %} 
{% if myForm.errors %}
<h1>Error en formulario</h1>
{% endif %}

<div style="width: 50%;">
  <form action="" method="POST">
    {% csrf_token %} {{ myForm.as_table }}

    <input type="submit" value="Actualizar" />
  </form>
</div>
</div>
{% endblock %}

AppOficina/templates/AppOficina/home.html
{% extends "AppOficina/plantilla.html" %} {% load static %} {% block main %}
<div >
  <h1>Casa</h1>
  <p>Acá va la info de los cursos</p>
</div>

{% endblock %}

AppOficina/templates/AppOficina/leerDesarrollador.html
{% extends "AppOficina/plantilla.html" %} {% load static %} {% block main %}

<div style="width: 60%">
  <h3>Desarrolladores</h3>
  <ul>
    {% for resultado in desarrolladores %}

    <li>
      <h4>{{ resultado.nombre}}</h4>
      <strong> Pais:</strong> {{resultado.pais}}
      <strong> Fundada:</strong> {{resultado.fundada}}
      <div style="padding: 10px 0px">
        <a
          style="
            color: white;
            padding: 1px 15px;
            background-color: red;
            opacity: 50%;
            text-decoration: none;
            margin-left: 10px;
            border-radius: 10px;
          "
          href="{% url 'eliminarDesarrollador' resultado.nombre %}"
        >
          <strong> Borrar </strong>
        </a>
        <a
          style="
            color: white;
            padding: 1px 15px;
            background-color: green;
            opacity: 50%;
            text-decoration: none;
            margin-left: 10px;
            border-radius: 10px;
          "
          href="{% url 'editarDesarrollador' resultado.nombre %}"
        >
          <strong> Editar </strong>
        </a>
      </div>
    </li>
    {% endfor %}
    <a href="{% url 'desarrollador'%}" style="text-decoration: none">
      <div
        style="
          padding: 10px 20px;
          background-color: blue;
          width: 200px;
          color: white;
          margin: 10px 5px;
          border-radius: 20px;
        "
      >
        Agregar Desarrollador
      </div>
    </a>
  </ul>
</div>
{% endblock %}

AppOficina/templates/AppOficina/leerPersonaje.html
{% extends "AppOficina/plantilla.html" %} {% load static %} {% block main %}

<div style="width: 60%">
  <h3>Videojuegos</h3>
  <ul>
    {% for resultado in personajes %}

    <li>
      <h4>{{ resultado.nombre}}</h4>
      <strong> Videojuego:</strong> {{resultado.videojuego}}
      <strong> Plataforma:</strong> {{resultado.plataforma}}
      <div style="padding: 10px 0px">
        <a
          style="
            color: white;
            padding: 1px 15px;
            background-color: red;
            opacity: 50%;
            text-decoration: none;
            margin-left: 10px;
            border-radius: 10px;
          "
          href="{% url 'eliminarPersonaje' resultado.nombre %}"
        >
          <strong> Borrar </strong>
        </a>
        <a
          style="
            color: white;
            padding: 1px 15px;
            background-color: green;
            opacity: 50%;
            text-decoration: none;
            margin-left: 10px;
            border-radius: 10px;
          "
          href="{% url 'editarPersonaje' resultado.nombre %}"
        >
          <strong> Editar </strong>
        </a>
      </div>
    </li>
    {% endfor %}
    <a href="{% url 'personaje'%}" style="text-decoration: none">
      <div
        style="
          padding: 10px 20px;
          background-color: blue;
          width: 200px;
          color: white;
          margin: 10px 5px;
          border-radius: 20px;
        "
      >
        Agregar Personaje
      </div>
    </a>
  </ul>
</div>
{% endblock %}

AppOficina/templates/AppOficina/login.html
{% extends "AppOficina/plantilla.html" %} {% load static %} 

{% block main %} 
{% if myForm.errors %}
<h1>Error en formulario</h1>
{% endif %}

<div>
  <form action="" method="POST">
    {% csrf_token %} {{ form.as_table }}

    <input type="submit" value="Ingresa" />
  </form>
</div>
{% endblock %}

AppOficina/templates/AppOficina/personajes.html
{% extends "AppOficina/plantilla.html" %} {% load static %}
{% block main %} 
{% if myForm.errors %}
<h1>Error en formulario</h1>
{% endif %}

<div >
  <form action="" method="POST">
    {% csrf_token %} {{ myForm.as_table }}

    <input type="submit" value="Registrar" />
  </form>
</div>
{% endblock %}

AppOficina/templates/AppOficina/plantilla.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="stylesheet"
      href="{% static 'AppOficina/assets/css/style.css' %}"
    />
    <title>Oficina Gamer</title>
    <meta
      name="description"
      content="Bienvenido a killetter. Estudio méxicano especializado en caligrafía, tipografía y lettering."
    />
    <meta name="keywords" content="DISEÑO, TIPOGRAFÍA, CALIGRAFÍA, LETTERING" />
    <!-- OPEN GRAPH -->
    <meta property="og:tipe" content="website" />
    <meta property="og:title" content="killetter" />
    <meta
      property="og:description"
      content="Estudio méxicano especializado en caligrafía, tipografía y lettering."
    />
    <meta property="og:name" content="Killetter Studio" />
    <!-- Favicon -->
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="{% static 'AppOficina/assets/img/favicons/favicon-16x16.png' %}"
    />
    <meta name="msapplication-TileColor" content="#ffffff" />
    <meta name="theme-color" content="#ffffff" />
  </head>
  <body>
    <header class="barHeader">
      <div class="logo">
        <a class="logoText" href="{% url 'home'%}">Oficina Gamer</a>
      </div>
      <nav class="navBar">
        <ul>
          <li><a href="{% url 'registro'%}">Contenido de Videojuegos</a></li>
          {% if request.user.is_authenticated %}
          <li><a href="{% url 'editarUser'%}"> Editar Usuario </a></li>
          <li><a href="{% url 'logout'%}"> Cerrar Sesión </a></li>
          <li
            style="
              text-decoration: none;
              font-size: 20px;
              text-align: center;
              color: #004a89;
              display: inline-block;
              padding: 5px 10px;
              border-bottom: rgba(0, 73, 137, 0) 1px solid;
            "
          >
            <a href="{% url 'avatar'%}">Hola {{ user.first_name }}</a>
          </li>
          {% with user.avatar_set.first as miAvatar %} {% if miAvatar %}
          <li>
            <div
              style="width: 50px; height: 50px; background-image: url('{{miAvatar.image.url}}');
              background-repeat:no-repeat;
              background-size:cover;
              background-position:center center;
              border-radius:50px"
            ></div>
          </li>
          {% endif %} {% endwith %} {% else %}
          <li><a href="{% url 'login'%}"> Iniciar Sesión </a></li>
          <li><a href="{% url 'Signout'%}"> Registrarse </a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main class="container" style="margin-top: 100px; width: 80%">
      {% block main %} {% endblock %}
    </main>

    <!-- Footer -->
    <footer class="barFooter">
      <div class="logo">
        <a class="logoTextFoot" href="{% url 'about'%}">Sobre mi</a>
      </div>
      <nav class="navBarFooter">
        <a href="https://www.instagram.com/killetter"
          ><img
            class="jello-vertical"
            src="{% static 'AppOficina/assets/icons/instagram-brands.svg' %}"
            alt="Logo de
          instagram"
        /></a>
        <a href="https://twitter.com/killettertype"
          ><img
            class="jello-vertical"
            src="{% static 'AppOficina/assets/icons/twitter-brands.svg' %}"
            alt="Logo de twitter"
        /></a>
        <a href="https://www.behance.net/killetter"
          ><img
            class="jello-vertical"
            src="{% static 'AppOficina/assets/icons/behance-brands.svg' %}"
            alt="Logo de behance"
        /></a>
        <a href="https://github.com/miglconts"
          ><img
            class="jello-vertical"
            src="{% static 'AppOficina/assets/icons/github-brands.svg' %}"
            alt="Logo de github"
        /></a>
      </nav>
    </footer>
  </body>
</html>

AppOficina/templates/AppOficina/resultadoDesarrollador.html
{% extends "AppOficina/plantilla.html" %} {% load static %} {% block main %}

<div>
  {% if consulta %}

  <h3>Resultados de la búsqueda: {{consulta}}</h3>
  <ul>
    {% for resultado in resultados %}

    <li>
      <h4>{{ resultado.nombre}}</h4>
      <strong> Fundada:</strong> {{resultado.fundada}}
      <strong> Pais:</strong> {{resultado.pais}}
    </li>

    {% endfor %}
  </ul>
  {% endif %}
</div>
{% endblock %}